# Generated by Django 3.2 on 2022-05-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_latesnews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weoffer',
            new_name='Ourserver',
        ),
    ]
