# Generated by Django 3.2 on 2022-05-27 06:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_gallery_ourproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourserver',
            name='content',
        ),
        migrations.AddField(
            model_name='ourserver',
            name='sub_title',
            field=models.CharField(default='sub1', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourserver',
            name='textfiled',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
