# Generated by Django 3.2 on 2022-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_contactservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactservice',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
