# Generated by Django 3.2 on 2022-05-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_contactservice_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='according',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
    ]
