# Generated by Django 3.2 on 2022-05-28 10:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20220528_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproject',
            name='according',
        ),
        migrations.RemoveField(
            model_name='ourproject',
            name='price',
        ),
        migrations.AddField(
            model_name='ourproject',
            name='textfiled',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
