# Generated by Django 3.2 on 2022-05-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_ourvision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourvision',
            name='image',
        ),
    ]
