# Generated by Django 3.2 on 2022-05-30 06:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_boardmeetingsagm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporategovernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='historymilestones')),
                ('title', models.CharField(max_length=200)),
                ('textfiled', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
