# Generated by Django 3.2 on 2022-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_corporategovernance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='reportFILE/')),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
