# Generated by Django 3.2 on 2022-05-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20220530_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsevents',
            new_name='Events',
        ),
    ]
