# Generated by Django 3.2 on 2022-06-04 05:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_expertteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertteams',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='gjghjghj', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
