# Generated by Django 3.2 on 2022-06-08 05:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymilestones',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='history', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
