# Generated by Django 3.2 on 2022-06-08 05:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_remove_historymilestones_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymilestones',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title'),
        ),
    ]
