# Generated by Django 3.2 on 2022-06-08 05:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_historymilestones_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymilestones',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='exit', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
