# Generated by Django 3.2 on 2022-06-08 06:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_alter_historymilestones_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmeetingsagm',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
        ),
    ]
