# Generated by Django 3.2 on 2022-06-09 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_brand_category_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotationinquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(default=1)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801711111000'.", regex='^\\+?1?\\d{11,14}$')])),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Quotation Inquiry',
                'verbose_name_plural': 'Quotation Inquiry',
            },
        ),
    ]
