# Generated by Django 3.2 on 2022-06-10 04:43

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_quotationinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardofDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='teams')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Board Of Directors',
                'verbose_name_plural': 'Board Of Directors',
            },
        ),
    ]
