# Generated by Django 3.2 on 2022-06-10 05:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_boardofdirector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertteams',
            options={'verbose_name': 'Expert Team Member', 'verbose_name_plural': 'Expert Team Member'},
        ),
        migrations.AlterField(
            model_name='boardofdirector',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='expertteams',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
