# Generated by Django 3.2 on 2022-06-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20220610_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='notice/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notice',
            },
        ),
    ]
