# Generated by Django 3.2 on 2022-06-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_auto_20220612_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmeetingsagm',
            name='image',
            field=models.ImageField(upload_to='Boardmeetingsagm'),
        ),
        migrations.AlterField(
            model_name='corporategovernance',
            name='image',
            field=models.ImageField(upload_to='Corporategovernance'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='Events'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
