# Generated by Django 3.2 on 2022-06-12 06:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_auto_20220612_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='hjgdkf', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
