# Generated by Django 3.2 on 2022-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_ourvision_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ourvision'),
        ),
    ]
