# Generated by Django 3.2 on 2022-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_ourreport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ourreport'),
        ),
    ]
