# Generated by Django 3.2 on 2022-07-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermodel',
            name='url_field',
            field=models.URLField(blank=True, null=True),
        ),
    ]
